/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hp' at '6/14/14 1:21 PM' with Gradle 1.12
 *
 * @author hp, @date 6/14/14 1:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
